# Generated by Django 4.0.4 on 2023-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbg_id', models.CharField(max_length=100)),
                ('views', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
