# Generated by Django 4.0.4 on 2023-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
